"""
One-off script: builds a single test document with a deliberately unresolvable
amount conflict (digits say one value, words say a completely different one —
not a clean 10x/100x/1000x scale error, so the comparator can't auto-recover
it). This is the exact scenario NEEDS_REVIEW exists for.

The synthetic dataset generated by synthetic/generate.py has ZERO documents
like this (confirmed: its expected_status is always APPROVED or
CHANGES_REQUESTED, never NEEDS_REVIEW) — so this is the only way to actually
test whether the 32B + amount-refinement changes affect this specific path.

Usage:
    python make_needs_review_test.py
Produces:
    needs_review_test.pdf   — upload this via /verify (or the website's
                               Verify Document button) against a case whose
                               expected sanction_amount matches NEITHER
                               6,350,000 nor 2,500,000 (see printed values).
"""

import sys
sys.path.insert(0, ".")

from pathlib import Path
from synthetic.generate import (
    _mahindra_data,
    build_mahindra_pdf,
    format_amount_doc,
    number_to_indian_words,
)

fields = _mahindra_data(idx=9999)

# Digits say Rs.25.00 lakhs (2,500,000). Words say Sixty Three Lakh Fifty
# Thousand (6,350,000). Neither is a clean 10x/100x/1000x multiple of the
# other, and neither will match the expected value we tell the caller to
# check against below — genuine, unresolvable conflict.
digits_amount = format_amount_doc(25.0)             # "Rs.25.00 lakhs" -> 2,500,000
words_amount  = number_to_indian_words(6_350_000)   # "Sixty Three Lakh Fifty Thousand"

conflicting_amount_string = f"{digits_amount} (Rupees {words_amount} Only)"

fields["sanction_amount"]     = conflicting_amount_string
fields["disbursement_amount"] = conflicting_amount_string  # keep both fields consistent

out_path = Path("needs_review_test.pdf")
build_mahindra_pdf(out_path, fields)

print(f"Built: {out_path.name} (in current directory)")
print()
print("Document prints:", conflicting_amount_string)
print()
print("To test this properly, verify it against an 'expected' sanction_amount /")
print("disbursement_amount that is NEITHER 2500000 NOR 6350000 — e.g. 4000000.")
print("Every other field (customer_name, LAN, application_id, branch, date, loan_type)")
print("matches what's printed on the doc, so with a genuinely-ambiguous amount and")
print("everything else correct, the ONLY correct verdict is NEEDS_REVIEW.")
print()
print("Fields on this document (for building the 'expected' dict to compare against):")
for key in ["customer_name", "bank_name", "loan_account_number", "application_id",
            "loan_type", "branch", "disbursement_date"]:
    print(f"  {key}: {fields[key]}")
